<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="prgDataAnalyse" Id="{6fb35069-0355-0863-25ed-8dde8197eca1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgDataAnalyse


VAR
	

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

]]></ST>
    </Implementation>
    <LineIds Name="prgDataAnalyse">
      <LineId Id="68" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="66" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>