<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="POU" Id="{18785d27-106c-0259-129f-d8430234070a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>