<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_SafeDiag" Id="{28431db4-d0e1-073b-2ee2-e5cdfa2aa643}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SafeDiag
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SafeDiag">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>