<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Window" Id="{4cf7a1dd-4be4-0676-17d1-6d8992ea43f1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FB_Window
VAR
END_VAR
VAR_INPUT
	dataAxis: typeDataAxis;
	optionA:typeVectorOptions;
	optionB:typeVectorOptions;
//	optionC:typeVectorOptions;
//	optionD:typeVectorOptions;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
	
	^
	value
	|
	|							C
	|			1_______________________________4
	|			|								|
	|			|								|
	|			|								|
	|			|								|
	|			|								|  
	|		A	|								|  B
	|			|								|
	|			|								|
	|			|								|
	|-----------|----------------line 			|
	|			|_______________________________|
	|			2								3
	|							D
	|							
	|							
	----------------------------------------------------------------time->
	1	2	3	4	5	6	7	8	9 	10 	11	12	13	14	15	16	17 etc
	
	Each side of a box has a entry point, check which vector the data
	passes into


*)


//loop around [4]ness for entire array of data
IF dataAxis.grabTime[4] = optionA.point2.PointXTime THEN //A2 //add in tolerance?
		//evaulate A2
		IF dataAxis.grabData[4] < optionA.point1 OR dataAxis.grabData[4] > optionA.point2 THEN
			//was true
			ELSE
			//was false
		END_IF
END_IF

IF dataAxis.grabTime[4] = optionA.point1.PointXTime THEN //A1 //add in tolerance?
		//evaulate A1
END_IF
///////////////////////////////////////////////////////////////////////////////////

]]></ST>
    </Implementation>
    <LineIds Name="FB_Window">
      <LineId Id="6" Count="30" />
      <LineId Id="53" Count="3" />
      <LineId Id="72" Count="1" />
      <LineId Id="75" Count="1" />
      <LineId Id="74" Count="0" />
      <LineId Id="57" Count="4" />
      <LineId Id="52" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>