<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="pouHMI" Id="{54e7270f-e089-40a6-a429-6d01839a041f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM pouHMI
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//all logic to control HMI
prgHMIcontrol();

//control Unit Screen
prgHMIUnits();

//logic for stations
prgHMIstations();

//call to read xml data
pouReadHMIMessages();


//call to read text lists into PLC memory arrays
prgReadTextList();


]]></ST>
    </Implementation>
    <LineIds Name="pouHMI">
      <LineId Id="5" Count="1" />
      <LineId Id="12" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="37" Count="1" />
      <LineId Id="34" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="22" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>