<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="pouReadHMIMessages" Id="{ce838f3d-32dc-4330-919e-70024cdd9543}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM pouReadHMIMessages
VAR


	openfile: FB_FILEOPEN;
	closefile: FB_FileClose;
	
	startOpeningFile: BOOL;

	OpenedFileNum: UINT;
	startRead: BOOL;
	startClosingfile: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actReadText"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">117L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeTerminator">
                        <o>
                          <n n="Input" />
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="Id">119L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">118L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">99L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeTerminator">{5f9848d3-568d-4cc5-9e31-8e28e9607ff1}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="actReadText" Id="{ef7559f8-d0a7-4bd6-9ac5-587f43038718}">
      <Implementation>
        <ST><![CDATA[


IF startRead THEN
	
	//self clear for 1 scan
	startRead:= FALSE;
	
	startOpeningFile := TRUE;
					
END_IF

//open file
openfile	(sNetId:=,
			sPathName:='C:\PLC\Messages\Mc_Alarms.XML',
			nMode:=FOPEN_MODEREAD,
			ePath:=PATH_GENERIC,
			bExecute:=startOpeningFile,
			tTimeout:=T#1S
			);
startOpeningFile := FALSE;		

//do something else here to read more of the file in
OpenedFileNum := openfile.hFile;


IF OpenedFileNum = 0 THEN
	startClosingfile:=TRUE;
END_IF


//close the file when read in the XML data
closefile	(sNetId:=,
			hFile:= OpenedFileNum,
			bExecute:=startClosingfile,
			tTimeout:=T#1S
			);
startClosingfile:=FALSE;


		
]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="pouReadHMIMessages.actReadText">
      <LineId Id="55" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="88" Count="1" />
      <LineId Id="59" Count="0" />
      <LineId Id="94" Count="1" />
      <LineId Id="90" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="57" Count="0" />
      <LineId Id="1" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="8" Count="3" />
      <LineId Id="14" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="81" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="97" Count="2" />
      <LineId Id="101" Count="0" />
      <LineId Id="104" Count="0" />
      <LineId Id="100" Count="0" />
      <LineId Id="96" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="68" Count="1" />
      <LineId Id="72" Count="1" />
      <LineId Id="85" Count="0" />
      <LineId Id="105" Count="1" />
      <LineId Id="46" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>