<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgHMIcontrol" Id="{f2bb902c-68c6-495b-ba1a-10a09cc0583e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgHMIcontrol
VAR
	tStationNumberIndex: UINT;
	tNumElementsPerScreen: UINT;
	tScreenElementsPerPage: UINT;
	tTrueStationIndex: UINT;
	retval: UDINT;
	tSizeOfMotionRow: UINT;
	tSizeOfMotionRowButtons: UINT;


	tNoMessagesOnMC: BOOL;
	retvalll: UDINT;

	CLK: BOOL;
	
	btnNext:R_TRIG;
	btnPrev:R_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"select station on HMI"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actPageControl"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">29L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">32L</v>
                          </o>
                          <v n="Id">31L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">30L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">28L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"calculate screen range"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actCalcScreenNumber"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">39L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">42L</v>
                          </o>
                          <v n="Id">41L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">40L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">38L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"call manual screen rows"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actCallMotionScreen"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">279L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">282L</v>
                          </o>
                          <v n="Id">281L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">280L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">278L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"calculate screen range"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actCalcMotionRowPosn"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">131L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">134L</v>
                          </o>
                          <v n="Id">133L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">132L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">130L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"call mode screen button hides"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actModeScreenBtnEnables"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">111L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">114L</v>
                          </o>
                          <v n="Id">113L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">112L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">110L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"call mode screen button hides"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"prgShowButtons"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">257L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">187L</v>
                          </o>
                          <v n="Id">186L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Program</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">258L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">183L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actEnableAlarms"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">191L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">194L</v>
                          </o>
                          <v n="Id">193L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">192L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">190L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actEnableWarning"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">198L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">201L</v>
                          </o>
                          <v n="Id">200L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">199L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">197L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actEnablePrompts"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">219L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">222L</v>
                          </o>
                          <v n="Id">221L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">220L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">218L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actAlarmListing"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">223L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"System.OneSecond"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">16</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">13L</v>
                          </o>
                          <v n="Id">12L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">224L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" />
                  <l2 n="Connectors" />
                  <v n="Id">14L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="actAlarmListing" Id="{fb653f66-9d37-4074-99d5-038a0db1f385}">
      <Implementation>
        <ST><![CDATA[//do nothing


//do something
//move station data into global data area for viewing
IF gHMIData.gStationSelected[1] THEN
	retvalll := MEMCPY(	destAddr:=	ADR(	gHMIData.gAlarmViewMsg), 
						srcAddr:=	ADR(	GlobalMessages.gListMsgS1), 
						n:=			SIZEOF(	GlobalMessages.gListMsgS1));
						
	retvalll := MEMCPY(	destAddr:=	ADR(	GlobalMessages.gHMIAlarmView), 
						srcAddr:=	ADR(	GlobalMessages.gS1AlarmView), 
						n:=			SIZEOF(	GlobalMessages.gS1AlarmView));
END_IF

IF gHMIData.gStationSelected[2] THEN
	retvalll := MEMCPY(	destAddr:=	ADR(	gHMIData.gAlarmViewMsg), 
						srcAddr:=	ADR(	GlobalMessages.gListMsgS2), 
						n:=			SIZEOF(	GlobalMessages.gListMsgS2));
						
	retvalll := MEMCPY(	destAddr:=	ADR(	GlobalMessages.gHMIAlarmView), 
						srcAddr:=	ADR(	GlobalMessages.gS2AlarmView), 
						n:=			SIZEOF(	GlobalMessages.gS2AlarmView));
END_IF

IF gHMIData.gStationSelected[3] THEN
	retvalll := MEMCPY(	destAddr:=	ADR(	gHMIData.gAlarmViewMsg), 
						srcAddr:=	ADR(	GlobalMessages.gListMsgS3), 
						n:=			SIZEOF(	GlobalMessages.gListMsgS3));

	retvalll := MEMCPY(	destAddr:=	ADR(	GlobalMessages.gHMIAlarmView), 
						srcAddr:=	ADR(	GlobalMessages.gS3AlarmView), 
						n:=			SIZEOF(	GlobalMessages.gS3AlarmView));
END_IF

IF gHMIData.gStationSelected[4] THEN
	retvalll := MEMCPY(	destAddr:=	ADR(	gHMIData.gAlarmViewMsg), 
						srcAddr:=	ADR(	GlobalMessages.gListMsgS4), 
						n:=			SIZEOF(	GlobalMessages.gListMsgS4));

	retvalll := MEMCPY(	destAddr:=	ADR(	GlobalMessages.gHMIAlarmView), 
						srcAddr:=	ADR(	GlobalMessages.gS4AlarmView), 
						n:=			SIZEOF(	GlobalMessages.gS4AlarmView));
END_IF

IF gHMIData.gStationSelected[5] THEN
	retvalll := MEMCPY(	destAddr:=	ADR(	gHMIData.gAlarmViewMsg), 
						srcAddr:=	ADR(	GlobalMessages.gListMsgS5), 
						n:=			SIZEOF(	GlobalMessages.gListMsgS5));

	retvalll := MEMCPY(	destAddr:=	ADR(	GlobalMessages.gHMIAlarmView), 
						srcAddr:=	ADR(	GlobalMessages.gS5AlarmView), 
						n:=			SIZEOF(	GlobalMessages.gS5AlarmView));

END_IF

IF gHMIData.gStationSelected[6] THEN
	retvalll := MEMCPY(	destAddr:=	ADR(	gHMIData.gAlarmViewMsg), 
						srcAddr:=	ADR(	GlobalMessages.gListMsgS6), 
						n:=			SIZEOF(	GlobalMessages.gListMsgS6));

	retvalll := MEMCPY(	destAddr:=	ADR(	GlobalMessages.gHMIAlarmView), 
						srcAddr:=	ADR(	GlobalMessages.gS6AlarmView), 
						n:=			SIZEOF(	GlobalMessages.gS6AlarmView));
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actCalcMotionRowPosn" Id="{d052a485-2ab5-4274-9ad1-f666fbdc1383}">
      <Implementation>
        <ST><![CDATA[//calaculate station index for pages
tTrueStationIndex := tStationNumberIndex + ((tScreenElementsPerPage * gHMIData.gActivePageNumber) -  tScreenElementsPerPage);

//calculate offset for row x
gHMIData.gRowElementOffset[1]:= tTrueStationIndex + ((gHMIDataConst.gNumberElementsPerRow * 1) - gHMIDataConst.gNumberElementsPerRow);
gHMIData.gRowElementOffset[2]:= tTrueStationIndex + ((gHMIDataConst.gNumberElementsPerRow * 2) - gHMIDataConst.gNumberElementsPerRow);
gHMIData.gRowElementOffset[3]:= tTrueStationIndex + ((gHMIDataConst.gNumberElementsPerRow * 3) - gHMIDataConst.gNumberElementsPerRow);
gHMIData.gRowElementOffset[4]:= tTrueStationIndex + ((gHMIDataConst.gNumberElementsPerRow * 4) - gHMIDataConst.gNumberElementsPerRow);
gHMIData.gRowElementOffset[5]:= tTrueStationIndex + ((gHMIDataConst.gNumberElementsPerRow * 5) - gHMIDataConst.gNumberElementsPerRow);
gHMIData.gRowElementOffset[6]:= tTrueStationIndex + ((gHMIDataConst.gNumberElementsPerRow * 6) - gHMIDataConst.gNumberElementsPerRow);


//move to global to be picked up by each row
gHMIMotionRows.gMotionRows.gMotionRow1.IndexLocation := gHMIData.gRowElementOffset[1];
gHMIMotionRows.gMotionRows.gMotionRow2.IndexLocation := gHMIData.gRowElementOffset[2];
gHMIMotionRows.gMotionRows.gMotionRow3.IndexLocation := gHMIData.gRowElementOffset[3];
gHMIMotionRows.gMotionRows.gMotionRow4.IndexLocation := gHMIData.gRowElementOffset[4];
gHMIMotionRows.gMotionRows.gMotionRow5.IndexLocation := gHMIData.gRowElementOffset[5];
gHMIMotionRows.gMotionRows.gMotionRow6.IndexLocation := gHMIData.gRowElementOffset[6];

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actCalcScreenNumber" Id="{6c34dbe5-12b3-4058-a71b-5a6feb4de7c0}">
      <Implementation>
        <ST><![CDATA[//create number for station
tStationNumberIndex := gHMIData.gActiveStationNumber * 10000;

//calculate number of elements per screen
tNumElementsPerScreen := gHMIDataConst.gNumberRowsPerPage * gHMIDataConst.gNumberElementsPerRow;

//calculate screen per page index
tScreenElementsPerPage := tNumElementsPerScreen  * 1;]]></ST>
      </Implementation>
    </Action>
    <Action Name="actCallMotionScreen" Id="{7fde1ebb-b0f7-4572-8651-feb24111554c}">
      <Implementation>
        <ST><![CDATA[//calculate byte offset - motions
tSizeOfMotionRow		:= gHMIData.gActivePageNumber * SIZEOF(gHMIMotionRows.gMotionRows);
tSizeOfMotionRow 		:= tSizeOfMotionRow - SIZEOF(gHMIMotionRows.gMotionRows);

//calculate byte offset - buttons
tSizeOfMotionRowButtons := gHMIData.gActivePageNumber * SIZEOF(gHMIMotionRows.gMotionRowButtons);
tSizeOfMotionRowButtons := tSizeOfMotionRowButtons - SIZEOF(gHMIMotionRows.gMotionRowButtons);

//move data based on station and page number
//Move feedback indicator data
//Move Button BOOL state back adr(S1_Global.MotionRow)
IF gHMIData.gStationSelected[1] THEN
	retval := memcpy(	destAddr:=	ADR(gHMIMotionRows.gMotionRows),
						srcAddr:=	ADR(S1_Global.MotionRow) + tSizeOfMotionRow,
						n:=			SIZEOF(gHMIMotionRows.gMotionRows)
						);
						
	retval := memcpy(	destAddr:=	ADR(S1_Global.MotionRowBtn) + tSizeOfMotionRowButtons,
						srcAddr:=	ADR(gHMIMotionRows.gMotionRowButtons),
						n:=			SIZEOF(gHMIMotionRows.gMotionRowButtons)
						);
END_IF

IF gHMIData.gStationSelected[2] THEN
	retval := memcpy(	destAddr:=	ADR(gHMIMotionRows.gMotionRows),
						srcAddr:=	ADR(S2_Global.MotionRow) + tSizeOfMotionRow,
						n:=			SIZEOF(gHMIMotionRows.gMotionRows)
						);
						
	retval := memcpy(	destAddr:=	ADR(S2_Global.MotionRowBtn) + tSizeOfMotionRowButtons,
						srcAddr:=	ADR(gHMIMotionRows.gMotionRowButtons),
						n:=			SIZEOF(gHMIMotionRows.gMotionRowButtons)
						);
END_IF

IF gHMIData.gStationSelected[3] THEN
	retval := memcpy(	destAddr:=	ADR(gHMIMotionRows.gMotionRows),
						srcAddr:=	ADR(S3_Global.MotionRow) + tSizeOfMotionRow,
						n:=			SIZEOF(gHMIMotionRows.gMotionRows)
						);
						
	retval := memcpy(	destAddr:=	ADR(S3_Global.MotionRowBtn) + tSizeOfMotionRowButtons,
						srcAddr:=	ADR(gHMIMotionRows.gMotionRowButtons),
						n:=			SIZEOF(gHMIMotionRows.gMotionRowButtons)
						);
END_IF

IF gHMIData.gStationSelected[4] THEN
	retval := memcpy(	destAddr:=	ADR(gHMIMotionRows.gMotionRows),
						srcAddr:=	ADR(S4_Global.MotionRow) + tSizeOfMotionRow,
						n:=			SIZEOF(gHMIMotionRows.gMotionRows)
						);
						
	retval := memcpy(	destAddr:=	ADR(S4_Global.MotionRowBtn) + tSizeOfMotionRowButtons,
						srcAddr:=	ADR(gHMIMotionRows.gMotionRowButtons),
						n:=			SIZEOF(gHMIMotionRows.gMotionRowButtons)
						);
END_IF

IF gHMIData.gStationSelected[5] THEN
	retval := memcpy(	destAddr:=	ADR(gHMIMotionRows.gMotionRows),
						srcAddr:=	ADR(S5_Global.MotionRow) + tSizeOfMotionRow,
						n:=			SIZEOF(gHMIMotionRows.gMotionRows)
						);
						
	retval := memcpy(	destAddr:=	ADR(S5_Global.MotionRowBtn) + tSizeOfMotionRowButtons,
						srcAddr:=	ADR(gHMIMotionRows.gMotionRowButtons),
						n:=			SIZEOF(gHMIMotionRows.gMotionRowButtons)
						);
END_IF

IF gHMIData.gStationSelected[6] THEN
	retval := memcpy(	destAddr:=	ADR(gHMIMotionRows.gMotionRows),
						srcAddr:=	ADR(S6_Global.MotionRow) + tSizeOfMotionRow,
						n:=			SIZEOF(gHMIMotionRows.gMotionRows)
						);
						
	retval := memcpy(	destAddr:=	ADR(S6_Global.MotionRowBtn) + tSizeOfMotionRowButtons,
						srcAddr:=	ADR(gHMIMotionRows.gMotionRowButtons),
						n:=			SIZEOF(gHMIMotionRows.gMotionRowButtons)
						);
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="actEnableAlarms" Id="{5245f169-b89e-4c0b-9dd8-16f27db7d894}">
      <Implementation>
        <ST><![CDATA[//enable alarm views on alarm state
IF GlobalMessages.gMsgMcStat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.McEnabled := FALSE;
ELSE
	gHMIData.gHideDisplayElementAlarmView.McEnabled := TRUE;
END_IF

//1
IF gHMIData.gStationSelected[1] AND GlobalMessages.gMsgS1Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S1Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS1Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S1Enabled := TRUE;
END_IF

//2
IF gHMIData.gStationSelected[2] AND GlobalMessages.gMsgS2Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S2Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS2Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S2Enabled := TRUE;
END_IF

//3
IF gHMIData.gStationSelected[3] AND GlobalMessages.gMsgS3Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S3Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS3Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S3Enabled := TRUE;
END_IF

//4
IF gHMIData.gStationSelected[4] AND GlobalMessages.gMsgS4Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S4Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS4Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S4Enabled := TRUE;
END_IF

//5
IF gHMIData.gStationSelected[5] AND GlobalMessages.gMsgS5Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S5Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS5Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S5Enabled := TRUE;
END_IF

//6
IF gHMIData.gStationSelected[6] AND GlobalMessages.gMsgS6Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S6Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS6Stat.IsAlarm THEN
	gHMIData.gHideDisplayElementAlarmView.S6Enabled := TRUE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS1Stat.IsAlarm THEN
	S1_Global.Data.Fault := TRUE;
	ELSE
	S1_Global.Data.Fault := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS2Stat.IsAlarm THEN
	S2_Global.Data.Fault := TRUE;
	ELSE
	S2_Global.Data.Fault := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS3Stat.IsAlarm THEN
	S3_Global.Data.Fault := TRUE;
	ELSE
	S3_Global.Data.Fault := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS4Stat.IsAlarm THEN
	S4_Global.Data.Fault := TRUE;
	ELSE
	S4_Global.Data.Fault := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS5Stat.IsAlarm THEN
	S5_Global.Data.Fault := TRUE;
	ELSE
	S5_Global.Data.Fault := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS6Stat.IsAlarm THEN
	S6_Global.Data.Fault := TRUE;
	ELSE
	S6_Global.Data.Fault := FALSE;
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actEnablePrompts" Id="{4c5fb0e8-5085-442b-9f23-b7a600b227a0}">
      <Implementation>
        <ST><![CDATA[//enable Prompt views on Prompt state
IF GlobalMessages.gMsgMcStat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.McEnabled := FALSE;
ELSE
	gHMIData.gHideDisplayElementPromptView.McEnabled := TRUE;
END_IF

//1
IF gHMIData.gStationSelected[1] AND GlobalMessages.gMsgS1Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S1Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS1Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S1Enabled := TRUE;
END_IF

//2
IF gHMIData.gStationSelected[2] AND GlobalMessages.gMsgS2Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S2Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS2Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S2Enabled := TRUE;
END_IF

//3
IF gHMIData.gStationSelected[3] AND GlobalMessages.gMsgS3Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S3Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS3Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S3Enabled := TRUE;
END_IF

//4
IF gHMIData.gStationSelected[4] AND GlobalMessages.gMsgS4Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S4Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS4Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S4Enabled := TRUE;
END_IF

//5
IF gHMIData.gStationSelected[5] AND GlobalMessages.gMsgS5Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S5Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS5Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S5Enabled := TRUE;
END_IF

//6
IF gHMIData.gStationSelected[6] AND GlobalMessages.gMsgS6Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S6Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS6Stat.IsPrompt THEN
	gHMIData.gHideDisplayElementPromptView.S6Enabled := TRUE;
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actEnableWarning" Id="{3cb1e8eb-ad76-414a-aa80-28e18b6bc457}">
      <Implementation>
        <ST><![CDATA[//enable Warning views on Warning state
IF GlobalMessages.gMsgMcStat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.McEnabled := FALSE;
ELSE
	gHMIData.gHideDisplayElementWarningView.McEnabled := TRUE;
END_IF

//1
IF gHMIData.gStationSelected[1] AND GlobalMessages.gMsgS1Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S1Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS1Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S1Enabled := TRUE;
END_IF

//2
IF gHMIData.gStationSelected[2] AND GlobalMessages.gMsgS2Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S2Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS2Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S2Enabled := TRUE;
END_IF

//3
IF gHMIData.gStationSelected[3] AND GlobalMessages.gMsgS3Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S3Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS3Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S3Enabled := TRUE;
END_IF

//4
IF gHMIData.gStationSelected[4] AND GlobalMessages.gMsgS4Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S4Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS4Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S4Enabled := TRUE;
END_IF

//5
IF gHMIData.gStationSelected[5] AND GlobalMessages.gMsgS5Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S5Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS5Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S5Enabled := TRUE;
END_IF

//6
IF gHMIData.gStationSelected[6] AND GlobalMessages.gMsgS6Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S6Enabled := FALSE;
END_IF

IF NOT GlobalMessages.gMsgS6Stat.IsWarning THEN
	gHMIData.gHideDisplayElementWarningView.S6Enabled := TRUE;
END_IF


//move set global fault
IF GlobalMessages.gMsgS1Stat.IsWarning THEN
	S1_Global.Data.Warning := TRUE;
	ELSE
	S1_Global.Data.Warning := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS2Stat.IsWarning THEN
	S2_Global.Data.Warning := TRUE;
	ELSE
	S2_Global.Data.Warning := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS3Stat.IsWarning THEN
	S3_Global.Data.Warning := TRUE;
	ELSE
	S3_Global.Data.Warning := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS4Stat.IsWarning THEN
	S4_Global.Data.Warning := TRUE;
	ELSE
	S4_Global.Data.Warning := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS5Stat.IsWarning THEN
	S5_Global.Data.Warning := TRUE;
	ELSE
	S5_Global.Data.Warning := FALSE;
END_IF

//move set global fault
IF GlobalMessages.gMsgS6Stat.IsWarning THEN
	S6_Global.Data.Warning := TRUE;
	ELSE
	S6_Global.Data.Warning := FALSE;
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actModeScreenBtnEnables" Id="{292c158a-5031-4703-bb01-bf615dd3670f}">
      <Implementation>
        <ST><![CDATA[//theme:LT-b1qXznKI
//hide/show buttons on mode screen

//row 0
gHMIButtons.btnFdbk.btn00Fdbk := FALSE;
gHMIButtons.btnFdbk.btn01Fdbk := FALSE;
gHMIButtons.btnFdbk.btn02Fdbk := FALSE;
gHMIButtons.btnFdbk.btn03Fdbk := FALSE;
gHMIButtons.btnFdbk.btn04Fdbk := FALSE;
gHMIButtons.btnFdbk.btn05Fdbk := FALSE;
gHMIButtons.btnFdbk.btn06Fdbk := FALSE;
gHMIButtons.btnFdbk.btn07Fdbk := FALSE;
gHMIButtons.btnFdbk.btn08Fdbk := FALSE;
gHMIButtons.btnFdbk.btn09Fdbk := FALSE;

//row 1
gHMIButtons.btnFdbk.btn10Fdbk := FALSE;
gHMIButtons.btnFdbk.btn11Fdbk := FALSE;
gHMIButtons.btnFdbk.btn12Fdbk := FALSE;
gHMIButtons.btnFdbk.btn12Fdbk := FALSE;
gHMIButtons.btnFdbk.btn13Fdbk := FALSE;
gHMIButtons.btnFdbk.btn14Fdbk := FALSE;
gHMIButtons.btnFdbk.btn15Fdbk := FALSE;
gHMIButtons.btnFdbk.btn16Fdbk := FALSE;
gHMIButtons.btnFdbk.btn17Fdbk := FALSE;
gHMIButtons.btnFdbk.btn18Fdbk := FALSE;
gHMIButtons.btnFdbk.btn19Fdbk := FALSE;

//row 2
gHMIButtons.btnFdbk.btn20Fdbk := FALSE;
gHMIButtons.btnFdbk.btn21Fdbk := FALSE;
gHMIButtons.btnFdbk.btn22Fdbk := FALSE;
gHMIButtons.btnFdbk.btn22Fdbk := FALSE;
gHMIButtons.btnFdbk.btn23Fdbk := FALSE;
gHMIButtons.btnFdbk.btn24Fdbk := FALSE;
gHMIButtons.btnFdbk.btn25Fdbk := FALSE;
gHMIButtons.btnFdbk.btn26Fdbk := FALSE;
gHMIButtons.btnFdbk.btn27Fdbk := FALSE;
gHMIButtons.btnFdbk.btn28Fdbk := FALSE;
gHMIButtons.btnFdbk.btn29Fdbk := FALSE;

//special row
gHMIButtons.btnFdbk.btnAutoCyclingFdbk := FALSE;
gHMIButtons.btnFdbk.btnIsHomeFdbk := FALSE;]]></ST>
      </Implementation>
    </Action>
    <Action Name="actPageControl" Id="{30c64ed5-f661-4d65-b1ea-51ade9043dc1}">
      <Implementation>
        <ST><![CDATA[//imply TRIG call
btnNext(clk:=gHMIButtons.btnNextPage);
btnPrev(clk:=gHMIButtons.btnPrevPage);


//next page
IF btnNext.Q THEN
	gHMIData.gActivePageNumber := gHMIData.gActivePageNumber + 1;
END_IF

//previous page
IF btnPrev.Q THEN
	gHMIData.gActivePageNumber := gHMIData.gActivePageNumber - 1;
END_IF

//apply limits
IF gHMIData.gActivePageNumber < 1 THEN
	gHMIData.gActivePageNumber := 1;
END_IF

//apply limits
IF gHMIData.gActivePageNumber > gHMIData.gMaxPageNumber THEN
	gHMIData.gActivePageNumber := gHMIData.gMaxPageNumber;
END_IF

//station 1 control
IF gHMIData.gStationSelected[1] THEN
	gHMIData.gMaxPageNumber := S1_Global.Data.NumberOfPages;
END_IF

//station 2 control
IF gHMIData.gStationSelected[2] THEN
	gHMIData.gMaxPageNumber := S2_Global.Data.NumberOfPages;
END_IF

//station 3 control
IF gHMIData.gStationSelected[3] THEN
	gHMIData.gMaxPageNumber := S3_Global.Data.NumberOfPages;
END_IF

//station 4 control
IF gHMIData.gStationSelected[4] THEN
	gHMIData.gMaxPageNumber := S4_Global.Data.NumberOfPages;
END_IF

//station 5 control
IF gHMIData.gStationSelected[5] THEN
	gHMIData.gMaxPageNumber := S5_Global.Data.NumberOfPages;
END_IF

//station 6 control
IF gHMIData.gStationSelected[6] THEN
	gHMIData.gMaxPageNumber := S6_Global.Data.NumberOfPages;
END_IF

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actPartStatus" Id="{cab25dde-a4a3-4552-af6a-583c332d34bc}">
      <Implementation>
        <ST><![CDATA[//may not need any of this, as the part data is moved to mc_global.part in each part process call
//move station data into global data area for viewing
IF gHMIData.gStationSelected[1] THEN
	retval := memcpy(	destAddr:=	ADR(Mc_Global.part),
						srcAddr:=	ADR(S1_Global.part),
						n:=			SIZEOF(S1_Global.part)
						);
END_IF

//move station data into global data area for viewing
IF gHMIData.gStationSelected[2] THEN
	retval := memcpy(	destAddr:=	ADR(Mc_Global.part),
						srcAddr:=	ADR(S2_Global.part),
						n:=			SIZEOF(S2_Global.part)
						);
END_IF

//move station data into global data area for viewing
IF gHMIData.gStationSelected[3] THEN
	retval := memcpy(	destAddr:=	ADR(Mc_Global.part),
						srcAddr:=	ADR(S3_Global.part),
						n:=			SIZEOF(S3_Global.part)
						);
END_IF

//move station data into global data area for viewing
IF gHMIData.gStationSelected[4] THEN
	retval := memcpy(	destAddr:=	ADR(Mc_Global.part),
						srcAddr:=	ADR(S4_Global.part),
						n:=			SIZEOF(S4_Global.part)
						);
END_IF

//move station data into global data area for viewing
IF gHMIData.gStationSelected[5] THEN
	retval := memcpy(	destAddr:=	ADR(Mc_Global.part),
						srcAddr:=	ADR(S5_Global.part),
						n:=			SIZEOF(S5_Global.part)
						);
END_IF

//move station data into global data area for viewing
IF gHMIData.gStationSelected[6] THEN
	retval := memcpy(	destAddr:=	ADR(Mc_Global.part),
						srcAddr:=	ADR(S6_Global.part),
						n:=			SIZEOF(S6_Global.part)
						);
END_IF

]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="prgHMIcontrol.actAlarmListing">
      <LineId Id="1" Count="0" />
      <LineId Id="14" Count="1" />
      <LineId Id="3" Count="0" />
      <LineId Id="48" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="53" Count="0" />
      <LineId Id="55" Count="1" />
      <LineId Id="54" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="17" Count="4" />
      <LineId Id="57" Count="0" />
      <LineId Id="59" Count="1" />
      <LineId Id="58" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="23" Count="4" />
      <LineId Id="62" Count="0" />
      <LineId Id="64" Count="1" />
      <LineId Id="63" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="29" Count="4" />
      <LineId Id="66" Count="0" />
      <LineId Id="68" Count="1" />
      <LineId Id="67" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="35" Count="4" />
      <LineId Id="76" Count="0" />
      <LineId Id="72" Count="1" />
      <LineId Id="70" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="41" Count="4" />
      <LineId Id="77" Count="0" />
      <LineId Id="79" Count="1" />
      <LineId Id="78" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="46" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actCalcMotionRowPosn">
      <LineId Id="1" Count="1" />
      <LineId Id="13" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="3" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="3" />
      <LineId Id="8" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="14" Count="5" />
      <LineId Id="21" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actCalcScreenNumber">
      <LineId Id="1" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="3" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actCallMotionScreen">
      <LineId Id="1" Count="1" />
      <LineId Id="84" Count="1" />
      <LineId Id="4" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="87" Count="0" />
      <LineId Id="8" Count="2" />
      <LineId Id="7" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="14" Count="3" />
      <LineId Id="19" Count="2" />
      <LineId Id="18" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="23" Count="10" />
      <LineId Id="22" Count="0" />
      <LineId Id="35" Count="10" />
      <LineId Id="34" Count="0" />
      <LineId Id="47" Count="10" />
      <LineId Id="46" Count="0" />
      <LineId Id="59" Count="10" />
      <LineId Id="58" Count="0" />
      <LineId Id="71" Count="10" />
      <LineId Id="70" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actEnableAlarms">
      <LineId Id="1" Count="2" />
      <LineId Id="7" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="16" Count="1" />
      <LineId Id="20" Count="7" />
      <LineId Id="19" Count="0" />
      <LineId Id="29" Count="7" />
      <LineId Id="28" Count="0" />
      <LineId Id="38" Count="7" />
      <LineId Id="37" Count="0" />
      <LineId Id="47" Count="7" />
      <LineId Id="46" Count="0" />
      <LineId Id="56" Count="7" />
      <LineId Id="55" Count="0" />
      <LineId Id="67" Count="1" />
      <LineId Id="65" Count="0" />
      <LineId Id="72" Count="2" />
      <LineId Id="70" Count="0" />
      <LineId Id="78" Count="5" />
      <LineId Id="77" Count="0" />
      <LineId Id="85" Count="5" />
      <LineId Id="84" Count="0" />
      <LineId Id="92" Count="5" />
      <LineId Id="91" Count="0" />
      <LineId Id="99" Count="5" />
      <LineId Id="98" Count="0" />
      <LineId Id="106" Count="5" />
      <LineId Id="105" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="64" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actEnablePrompts">
      <LineId Id="1" Count="2" />
      <LineId Id="7" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="16" Count="1" />
      <LineId Id="20" Count="7" />
      <LineId Id="19" Count="0" />
      <LineId Id="29" Count="7" />
      <LineId Id="28" Count="0" />
      <LineId Id="38" Count="7" />
      <LineId Id="37" Count="0" />
      <LineId Id="47" Count="7" />
      <LineId Id="46" Count="0" />
      <LineId Id="56" Count="7" />
      <LineId Id="55" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="64" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actEnableWarning">
      <LineId Id="1" Count="2" />
      <LineId Id="7" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="4" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="15" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="16" Count="1" />
      <LineId Id="20" Count="7" />
      <LineId Id="19" Count="0" />
      <LineId Id="29" Count="7" />
      <LineId Id="28" Count="0" />
      <LineId Id="38" Count="7" />
      <LineId Id="37" Count="0" />
      <LineId Id="47" Count="7" />
      <LineId Id="46" Count="0" />
      <LineId Id="56" Count="7" />
      <LineId Id="55" Count="0" />
      <LineId Id="66" Count="42" />
      <LineId Id="65" Count="0" />
      <LineId Id="64" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actModeScreenBtnEnables">
      <LineId Id="79" Count="0" />
      <LineId Id="1" Count="0" />
      <LineId Id="12" Count="1" />
      <LineId Id="2" Count="9" />
      <LineId Id="50" Count="2" />
      <LineId Id="73" Count="0" />
      <LineId Id="53" Count="11" />
      <LineId Id="74" Count="0" />
      <LineId Id="65" Count="7" />
      <LineId Id="38" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="77" Count="1" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actPageControl">
      <LineId Id="5" Count="0" />
      <LineId Id="1" Count="1" />
      <LineId Id="6" Count="1" />
      <LineId Id="4" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="13" Count="1" />
      <LineId Id="10" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="15" Count="1" />
      <LineId Id="3" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="20" Count="0" />
      <LineId Id="24" Count="3" />
      <LineId Id="23" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="30" Count="1" />
      <LineId Id="59" Count="0" />
      <LineId Id="35" Count="2" />
      <LineId Id="34" Count="0" />
      <LineId Id="60" Count="0" />
      <LineId Id="39" Count="2" />
      <LineId Id="38" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="43" Count="2" />
      <LineId Id="42" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="47" Count="2" />
      <LineId Id="46" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="51" Count="2" />
      <LineId Id="50" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="58" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIcontrol.actPartStatus">
      <LineId Id="12" Count="1" />
      <LineId Id="2" Count="4" />
      <LineId Id="1" Count="0" />
      <LineId Id="15" Count="6" />
      <LineId Id="14" Count="0" />
      <LineId Id="23" Count="6" />
      <LineId Id="22" Count="0" />
      <LineId Id="31" Count="6" />
      <LineId Id="30" Count="0" />
      <LineId Id="39" Count="6" />
      <LineId Id="38" Count="0" />
      <LineId Id="47" Count="6" />
      <LineId Id="46" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="62" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>