<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgHMIUnits" Id="{9c8f538d-0cac-44e6-9e25-d7758a4182c4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgHMIUnits
VAR
	tTrueUnitIndex: UINT;
	tSizeOfUnitRow: UINT;
	tSizeOfUnitRowButtons: UINT;
	tStationNumberIndexUnit: UINT;
	tScreenElementsPerPageUnit: UINT;
	tNumElementsPerScreen: UINT;
	retval: UDINT;
	nextPage: R_TRIG;
	PrevPage: R_TRIG;
END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"Control for Units screen"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">true</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"???"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">33L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"???"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">32L</v>
                        </o>
                        <v n="Id">31L</v>
                      </o>
                      <v n="Id">34L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">30L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actPageControlUnit"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">36L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">39L</v>
                          </o>
                          <v n="Id">38L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">37L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">35L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actCalcUnitScreenNumber"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">16L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">19L</v>
                          </o>
                          <v n="Id">18L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">17L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">15L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"contains MEMCPY, call before inserting data later to the hmi row"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actCallUnitScreen"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">21L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">24L</v>
                          </o>
                          <v n="Id">23L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">22L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">20L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"contains move into block data, move after the memcpy"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actCalcUnitRowPosn"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">26L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"System.PulseHundredMilliSecond"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <v n="Id">28L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">27L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">25L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">true</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"???"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">8L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeOperand">
                        <o n="Operand" t="Operand">
                          <v n="Operand">"???"</v>
                          <v n="Type">"BOOL"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">true</v>
                          <v n="IsInstance">false</v>
                          <v n="Id">7L</v>
                        </o>
                        <v n="Id">6L</v>
                      </o>
                      <v n="Id">9L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">5L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="actCalcUnitRowPosn" Id="{0ed1bd8f-f015-4a6a-985d-05d471409cfd}">
      <Implementation>
        <ST><![CDATA[//calculate station index for pages
tTrueUnitIndex :=	tStationNumberIndexUnit +
					(tScreenElementsPerPageUnit * gHMIUnits.gUnitActivePageNumber) -  tScreenElementsPerPageUnit;
					
//calculate offset for row x
gHMIUnits.gUnitRowElementOffset[1] :=	tTrueUnitIndex + 
										(gHMIDataConst.gNumberElementsPerRow * 1) - gHMIDataConst.gNumberElementsPerRow;

gHMIUnits.gUnitRowElementOffset[2] :=	tTrueUnitIndex + 
										(gHMIDataConst.gNumberElementsPerRow * 2) - gHMIDataConst.gNumberElementsPerRow;

gHMIUnits.gUnitRowElementOffset[3] :=	tTrueUnitIndex + 
										(gHMIDataConst.gNumberElementsPerRow * 3) - gHMIDataConst.gNumberElementsPerRow;

gHMIUnits.gUnitRowElementOffset[4] :=	tTrueUnitIndex + 
										(gHMIDataConst.gNumberElementsPerRow * 4) - gHMIDataConst.gNumberElementsPerRow;

gHMIUnits.gUnitRowElementOffset[5] :=	tTrueUnitIndex + 
										(gHMIDataConst.gNumberElementsPerRow * 5) - gHMIDataConst.gNumberElementsPerRow;

gHMIUnits.gUnitRowElementOffset[6] :=	tTrueUnitIndex + 
										(gHMIDataConst.gNumberElementsPerRow * 6) - gHMIDataConst.gNumberElementsPerRow;
				
//move to global to be picked up by each row					
gHMIUnits.gUnitRows.gMotionRow1.IndexLocation := gHMIUnits.gUnitRowElementOffset[1];
gHMIUnits.gUnitRows.gMotionRow2.IndexLocation := gHMIUnits.gUnitRowElementOffset[2];
gHMIUnits.gUnitRows.gMotionRow3.IndexLocation := gHMIUnits.gUnitRowElementOffset[3];
gHMIUnits.gUnitRows.gMotionRow4.IndexLocation := gHMIUnits.gUnitRowElementOffset[4];
gHMIUnits.gUnitRows.gMotionRow5.IndexLocation := gHMIUnits.gUnitRowElementOffset[5];
gHMIUnits.gUnitRows.gMotionRow6.IndexLocation := gHMIUnits.gUnitRowElementOffset[6];
]]></ST>
      </Implementation>
    </Action>
    <Action Name="actCalcUnitScreenNumber" Id="{b6e80cd0-cc91-4db9-8a87-842cacbe5d37}">
      <Implementation>
        <ST><![CDATA[//create number for station
tStationNumberIndexUnit	:= 1 * 10000; //declare math for now


//calculate number of elements per screen
tNumElementsPerScreen	:= gHMIDataConst.gNumberRowsPerPage * gHMIDataConst.gNumberElementsPerRow;

//calculate screen per page index
tScreenElementsPerPageUnit := tNumElementsPerScreen * 1; //declare math for future use]]></ST>
      </Implementation>
    </Action>
    <Action Name="actCallUnitScreen" Id="{e039fd61-b4bb-4708-9a6d-dd78cbee8b4d}">
      <Implementation>
        <ST><![CDATA[//calculate byte offset - motions
tSizeOfUnitRow := gHMIData.gActivePageNumber * SIZEOF(gHMIUnits.gUnitRows); //for pointer use
tSizeOfUnitRow := tSizeOfUnitRow - SIZEOF(gHMIUnits.gUnitRows);

//calculate byte offset - buttons
tSizeOfUnitRowButtons := gHMIData.gActivePageNumber * SIZEOF(gHMIUnits.gUnitButtons);
tSizeOfUnitRowButtons := tSizeOfUnitRowButtons - SIZEOF(gHMIUnits.gUnitButtons);

//move data based on station and page number
//Move feedback indicator data
//Move Button BOOL state back adr(S1_Global.MotionRow)
MEMCPY(	destAddr	:= ADR(gHMIUnits.gUnitRows),
		srcAddr		:= ADR(Mc_Global.UnitRow) + tSizeOfUnitRow,
		n			:= SIZEOF(gHMIData.gLangRows)
		);

MEMCPY(	destAddr	:= ADR(Mc_Global.UnitRowBtn) + tSizeOfUnitRowButtons,
		srcAddr		:= ADR(gHMIUnits.gUnitButtons),
		n			:= SIZEOF(gHMIUnits.gUnitButtons)
		);		
	
]]></ST>
      </Implementation>
    </Action>
    <Action Name="actPageControlUnit" Id="{a7da9a64-1712-4c8f-8f04-23c77db3b428}">
      <Implementation>
        <ST><![CDATA[//next page
nextPage(CLK	:= gHMIButtons.btnNextPage);
IF nextPage.Q THEN
	gHMIUnits.gUnitActivePageNumber	:=	gHMIUnits.gUnitActivePageNumber + 1;
END_IF

//previous page
PrevPage(CLK	:= gHMIButtons.btnPrevPage);
IF PrevPage.Q THEN
	gHMIUnits.gUnitActivePageNumber := gHMIUnits.gUnitActivePageNumber - 1;
END_IF



//apply limits
IF gHMIUnits.gUnitActivePageNumber < 1 THEN
	gHMIUnits.gUnitActivePageNumber := 1;
END_IF
	
IF gHMIUnits.gUnitActivePageNumber > gHMIUnits.gUnitMaxPageNumber THEN
	gHMIUnits.gUnitActivePageNumber := 1;
END_IF

gHMIUnits.gUnitMaxPageNumber := Mc_Global.Data.NumberOfPages;]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="prgHMIUnits.actCalcUnitRowPosn">
      <LineId Id="2" Count="29" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIUnits.actCalcUnitScreenNumber">
      <LineId Id="2" Count="7" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIUnits.actCallUnitScreen">
      <LineId Id="2" Count="20" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIUnits.actPageControlUnit">
      <LineId Id="2" Count="22" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>