<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="prgHMIstations" Id="{544d1eda-e916-4526-a80c-c42c36049926}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prgHMIstations
VAR
		tAllStations: BOOL;
	tUsestaions: BOOL;
	btnselectalltrig: R_TRIG;
	btnselall: F_TRIG;
	btnselS1: R_TRIG;
	btnselS2: R_TRIG;
	btnselS3: R_TRIG;
	btnselS4: R_TRIG;
	btnselS5: R_TRIG;
	btnselS6: R_TRIG;

END_VAR
]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"resume last selection
wip"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actResumeStationSelect"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">33L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"FALSE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">36L</v>
                          </o>
                          <v n="Id">35L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">34L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">32L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"select station on HMI"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actStationSelected"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">11L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <n />
                          <o>
                            <v n="Operand">"???"</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">true</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">13L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">false</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">15L</v>
                          </o>
                          <v n="Id">14L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">12L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">10L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">"select all station on HMI"</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actAllStationsSelected"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">26L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeOperand">
                        <o>
                          <o n="Operand" t="Operand">
                            <v n="Operand">"TRUE"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">"Constant_Address_Serialization_Value"</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">29L</v>
                          </o>
                          <v n="Id">28L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">27L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">25L</v>
                </o>
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeBox">
                    <o>
                      <v n="BoxType">"actStationEnables"</v>
                      <o n="Instance" t="Operand">
                        <n n="Operand" />
                        <v n="Type">""</v>
                        <v n="Comment">""</v>
                        <v n="SymbolComment">""</v>
                        <v n="Address">""</v>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <v n="LValue">false</v>
                        <v n="Boolean">false</v>
                        <v n="IsInstance">true</v>
                        <v n="Id">58L</v>
                      </o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems">
                          <n />
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <n n="InputFlags" />
                      <l2 n="InputItems" cet="BoxTreeTerminator">
                        <o>
                          <n n="Input" />
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="Id">60L</v>
                        </o>
                      </l2>
                      <o n="InputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>EN</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <o n="OutputParam" t="ParamList">
                        <l2 n="Names" cet="String">
                          <v>ENO</v>
                        </l2>
                        <l2 n="Types" cet="String">
                          <v>BOOL</v>
                        </l2>
                      </o>
                      <v n="CallType" t="Operator">Action</v>
                      <v n="EN">true</v>
                      <v n="ENO">true</v>
                      <n n="STSnippet" />
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="ProvidesSTSnippet">false</v>
                      <v n="Id">59L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">42L</v>
                </o>
              </l2>
              <v n="BranchCounter">0</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="BoxTreeTerminator">{5f9848d3-568d-4cc5-9e31-8e28e9607ff1}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
    <Action Name="actAllStationsSelected" Id="{fc9cc28c-94de-4892-8b94-333e8721262f}">
      <Implementation>
        <ST><![CDATA[//all station feedback
IF	gHMIData.gStationSelected[1]	AND	
	gHMIData.gStationSelected[2]	AND 
	gHMIData.gStationSelected[3]	AND
	gHMIData.gStationSelected[4]	AND
	gHMIData.gStationSelected[5]	AND
	gHMIData.gStationSelected[6]	
	THEN
		gHMIButtons.btnAllStationsSelected := TRUE;
	ELSE
		gHMIButtons.btnAllStationsSelected := FALSE;
END_IF

//select all stations
btnselectalltrig(CLK:= gHMIButtons.btnSelectAll);
IF btnselectalltrig.Q AND NOT gHMIButtons.btnAllStationsSelected THEN
	gHMIData.gStationSelected[1] := TRUE;
	gHMIData.gStationSelected[2] := TRUE;
	gHMIData.gStationSelected[3] := TRUE;
	gHMIData.gStationSelected[4] := TRUE;
	gHMIData.gStationSelected[5] := TRUE;
	gHMIData.gStationSelected[6] := TRUE;	
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="actResumeStationSelect" Id="{addf1aca-2153-49c7-a870-c5b6bbbacd8b}">
      <Implementation>
        <ST><![CDATA[//all station feedback
//on select all button falling
btnselall(CLK:= gHMIButtons.btnSelectAll);
IF 	btnselall.Q 					AND
	gHMIData.gStationSelected[1]	AND 
	gHMIData.gStationSelected[2]	AND 
	gHMIData.gStationSelected[3]	AND 
	gHMIData.gStationSelected[4]	AND 
	gHMIData.gStationSelected[5]	AND 
	gHMIData.gStationSelected[6]	 
	THEN

	//clear out selected	
	IF gHMIData.gActiveStationNumber > 1 THEN
		gHMIData.gStationSelected[1] := FALSE;
		gHMIData.gStationSelected[2] := FALSE;
		gHMIData.gStationSelected[3] := FALSE;
		gHMIData.gStationSelected[4] := FALSE;
		gHMIData.gStationSelected[5] := FALSE;
		gHMIData.gStationSelected[6] := FALSE;
	END_IF
	
	//select correct station
	CASE gHMIData.gActiveStationNumber OF
		1:
		gHMIData.gStationSelected[1] := TRUE;
		2:
		gHMIData.gStationSelected[2] := TRUE;
		3:
		gHMIData.gStationSelected[3] := TRUE;
		4:
		gHMIData.gStationSelected[4] := TRUE;
		5:
		gHMIData.gStationSelected[5] := TRUE;
		6:
		gHMIData.gStationSelected[6] := TRUE;
	END_CASE
END_IF
]]></ST>
      </Implementation>
    </Action>
    <Action Name="actStationEnables" Id="{401c3089-158a-4e3f-ba0a-795f1a2a44bf}">
      <Implementation>
        <ST><![CDATA[//disable all stations and let station calls enable on a per-scan basis
gHMIData.gStationEnabled[1]:= System.gSetup.stationEnable[1];
gHMIData.gStationEnabled[2]:= System.gSetup.stationEnable[2];
gHMIData.gStationEnabled[3]:= System.gSetup.stationEnable[3];
gHMIData.gStationEnabled[4]:= System.gSetup.stationEnable[4];
gHMIData.gStationEnabled[5]:= System.gSetup.stationEnable[5];
gHMIData.gStationEnabled[6]:= System.gSetup.stationEnable[6];

]]></ST>
      </Implementation>
    </Action>
    <Action Name="actStationSelected" Id="{d08ce5bd-f825-4aad-9abb-495ce6676e1e}">
      <Implementation>
        <ST><![CDATA[//select station on HMI
//theme:czWR1tA8oB0

btnselS1(clk:=gHMIButtons.btnSelectStation1);
btnselS2(clk:=gHMIButtons.btnSelectStation2);
btnselS3(clk:=gHMIButtons.btnSelectStation3);
btnselS4(clk:=gHMIButtons.btnSelectStation4);
btnselS5(clk:=gHMIButtons.btnSelectStation5);
btnselS6(clk:=gHMIButtons.btnSelectStation6);


//if any button pressed, clear down station memory and prepare for new station selected data
IF	btnselS1.Q OR
	btnselS2.Q OR
	btnselS3.Q OR
	btnselS4.Q OR
	btnselS5.Q OR
	btnselS6.Q
	THEN
		MEMSET(	destAddr:= ADR(gHMIData.gStationSelected),
				fillByte:= 16#0,
				n		:= SIZEOF(gHMIData.gStationSelected)
				);
		gHMIData.gActivePageNumber := 1;
END_IF

//move in correct data next in scan
IF btnselS1.Q THEN
	gHMIData.gActiveStationNumber := 1;
	gHMIData.gStationSelected[1] := TRUE;
END_IF

IF btnselS2.Q THEN
	gHMIData.gActiveStationNumber := 2;
	gHMIData.gStationSelected[2] := TRUE;
END_IF

IF btnselS3.Q THEN
	gHMIData.gActiveStationNumber := 3;
	gHMIData.gStationSelected[3] := TRUE;
END_IF

IF btnselS4.Q THEN
	gHMIData.gActiveStationNumber := 4;
	gHMIData.gStationSelected[4] := TRUE;
END_IF

IF btnselS5.Q THEN
	gHMIData.gActiveStationNumber := 5;
	gHMIData.gStationSelected[5] := TRUE;
END_IF

IF btnselS6.Q THEN
	gHMIData.gActiveStationNumber := 6;
	gHMIData.gStationSelected[6] := TRUE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="prgHMIstations.actAllStationsSelected">
      <LineId Id="1" Count="1" />
      <LineId Id="12" Count="0" />
      <LineId Id="6" Count="3" />
      <LineId Id="11" Count="0" />
      <LineId Id="13" Count="2" />
      <LineId Id="5" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="21" Count="1" />
      <LineId Id="24" Count="4" />
      <LineId Id="23" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIstations.actResumeStationSelect">
      <LineId Id="1" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="4" Count="1" />
      <LineId Id="7" Count="4" />
      <LineId Id="13" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="14" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="19" Count="5" />
      <LineId Id="28" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="35" Count="9" />
      <LineId Id="34" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIstations.actStationEnables">
      <LineId Id="1" Count="1" />
      <LineId Id="4" Count="3" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="3" Count="0" />
    </LineIds>
    <LineIds Name="prgHMIstations.actStationSelected">
      <LineId Id="59" Count="2" />
      <LineId Id="1" Count="0" />
      <LineId Id="3" Count="4" />
      <LineId Id="27" Count="1" />
      <LineId Id="10" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="13" Count="3" />
      <LineId Id="18" Count="1" />
      <LineId Id="21" Count="3" />
      <LineId Id="12" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="29" Count="1" />
      <LineId Id="32" Count="1" />
      <LineId Id="35" Count="3" />
      <LineId Id="34" Count="0" />
      <LineId Id="40" Count="3" />
      <LineId Id="39" Count="0" />
      <LineId Id="45" Count="3" />
      <LineId Id="44" Count="0" />
      <LineId Id="50" Count="3" />
      <LineId Id="49" Count="0" />
      <LineId Id="55" Count="3" />
      <LineId Id="54" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>